<ul class="contact-links">
	<?php /*
	<li class="first">
		<a href="tel:<?php echo Mage::getStoreConfig('general/store_information/phone'); ?>">CALL US: <?php echo Mage::getStoreConfig('general/store_information/phone'); ?></a>
	</li>
	*/?>
	<li>
        <a href="http://blog.snowbotica.com"><?php echo $this->__('BLOG') ?></a>
	</li>
    <li class="last">
		<a href="<?php echo $this->getUrl('contact')?>"><?php echo $this->__('CONTACT') ?></a>
    </li>
</ul>
